<?php
ini_set('display_errors', 1);
ini_set('memory_limit','1000M'); 
<<<<<<< HEAD
set_time_limit(0);
include "mysql_con.php";

echo "<HTML><BODY>";
$counter =0;
    $sql = "SELECT * FROM tbl_review";
    $result=mysqli_query($con,$sql);
	echo "<table border='1'>";
	//echo "<tr><td>New ID</td><td>Old ID</td><td>Type</td><td>Title</td><td>AuthorID</td><td>Created Date</td><td>Pending</td><td>Beta Approved</td><td>Alpha Approved</td><td>Tags</td><td>Views</td><td>Bites</td></tr>";
    while($row = $result->fetch_assoc()) {
    	
		$Usersql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$Usersql);
		$rowr= mysqli_fetch_row($resultr);
		echo "<tr>";
		echo "<td>";
		$stmt = mysqli_prepare($con, "INSERT INTO tbl_article (`legacyID`, `article_type`, `title`, `authorUserFK`, `createdate`, `pending`, `beta_approved`, `alpha_approved`, `tags`, `views`, `bites`) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
		$id=$row['id'];
		$type=$row['article_type'][0];
		$title=$row['title'];
		$authID=$rowr[0];
		$date=$row['createdate'];
		$pending=($row['pending']=='true');
		$beta=($row['beta_approved']=='true');
		$alpha=($row['alpha_approved']=='true');
		$tags=$row['tags'];
		$views=$row['views']; 
		$bites=$row['bites'];
		mysqli_stmt_bind_param($stmt, "ississsssii", $id, $type, $title, $authID, $date, $pending, $beta, $alpha, $tags, $views, $bites);
		mysqli_stmt_execute($stmt);
  		echo($id." | | ".mysqli_error($con));
    	$tempSQL="UPDATE tbl_review SET articleIDFK=".mysqli_insert_id($con)." WHERE id =".$row['id'];
    	mysqli_query($con,$tempSQL);
		echo "</td>";
		echo "<td>";
    	$counter++;
		/*echo $counter."<br />";
		echo $row["id"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["article_type"][0]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["title"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $rowr[0];
		echo "</td>";
		echo "<td>";
		echo $row["createdate"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["pending"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["beta_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["alpha_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["tags"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["views"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["bites"]."<br />";
		echo "</td>";
		echo "</tr>";*/
=======
include "mysql_con.php";

echo "<HTML><BODY>";

    $sql = "SELECT * FROM tbl_review";
    $result=mysqli_query($con,$sql);
	echo "<table border='1'>";
    while($row = $result->fetch_assoc()) {
	echo "<tr>";
	echo "<td>";
	echo $row["id"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["article_type"][0]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["title"]."<br />";
	echo "</td>";
	echo "<td>";
	$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
	$rowr= mysqli_fetch_row($resultr);
	echo $rowr[0];
	echo "</td>";
	echo "<td>";
	echo $row["createdate"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["pending"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["beta_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["alpha_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["tags"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["views"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["bites"]."<br />";
	echo "</td>";
	echo "</tr>";
>>>>>>> 3b252456cedc9e1e2a4528e19dbbf0e4acfcb9eb
    }
	

    $sql = "SELECT * FROM tbl_opinion";
    $result=mysqli_query($con,$sql);
    while($row = $result->fetch_assoc()) {
<<<<<<< HEAD
    	
		$Usersql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$Usersql);
		$rowr= mysqli_fetch_row($resultr);
		echo "<tr>";
		echo "<td>";
		$stmt = mysqli_prepare($con, "INSERT INTO tbl_article (`legacyID`, `article_type`, `title`, `authorUserFK`, `createdate`, `pending`, `beta_approved`, `alpha_approved`, `tags`, `views`, `bites`) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
		$id=$row['id'];
		$type=$row['article_type'][0];
		$title=$row['title'];
		$authID=$rowr[0];
		$date=$row['createdate'];
		$pending=($row['pending']=='true');
		$beta=($row['beta_approved']=='true');
		$alpha=($row['alpha_approved']=='true');
		$tags=$row['tags'];
		$views=$row['views']; 
		$bites=$row['bites'];
		mysqli_stmt_bind_param($stmt, "ississsssii", $id, $type, $title, $authID, $date, $pending, $beta, $alpha, $tags, $views, $bites);
		mysqli_stmt_execute($stmt);
  		echo($id." | | ".mysqli_error($con));
    	$tempSQL="UPDATE tbl_opinion SET articleIDFK=".mysqli_insert_id($con)." WHERE id =".$row['id'];
    	mysqli_query($con,$tempSQL);
		echo "</td>";
		echo "<td>";
    	/*$counter++;
		echo "<tr>";
		echo "<td>";
		echo $counter."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["id"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["article_type"][0]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["title"]."<br />";
		echo "</td>";
		echo "<td>";
		$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
		$rowr= mysqli_fetch_row($resultr);
		echo $rowr[0];
		echo "</td>";
		echo "<td>";
		echo $row["createdate"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["pending"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["beta_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["alpha_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["tags"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["views"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["bites"]."<br />";
		echo "</td>";
		echo "</tr>";*/
=======
	echo "<tr>";
	echo "<td>";
	echo $row["id"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["article_type"][0]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["title"]."<br />";
	echo "</td>";
	echo "<td>";
	$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
	$rowr= mysqli_fetch_row($resultr);
	echo $rowr[0];
	echo "</td>";
	echo "<td>";
	echo $row["createdate"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["pending"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["beta_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["alpha_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["tags"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["views"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["bites"]."<br />";
	echo "</td>";
	echo "</tr>";
>>>>>>> 3b252456cedc9e1e2a4528e19dbbf0e4acfcb9eb
	
    }
    $sql = "SELECT * FROM tbl_news";
    $result=mysqli_query($con,$sql);
    while($row = $result->fetch_assoc()) {
<<<<<<< HEAD
    	
		$Usersql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$Usersql);
		$rowr= mysqli_fetch_row($resultr);
		echo "<tr>";
		echo "<td>";
		$stmt = mysqli_prepare($con, "INSERT INTO tbl_article (`legacyID`, `article_type`, `title`, `authorUserFK`, `createdate`, `pending`, `beta_approved`, `alpha_approved`, `tags`, `views`, `bites`) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
		$id=$row['id'];
		$type=$row['article_type'][0];
		$title=$row['title'];
		$authID=$rowr[0];
		$date=$row['createdate'];
		$pending=($row['pending']=='true');
		$beta=($row['beta_approved']=='true');
		$alpha=($row['alpha_approved']=='true');
		$tags=$row['tags'];
		$views=$row['views']; 
		$bites=$row['bites'];
		mysqli_stmt_bind_param($stmt, "ississsssii", $id, $type, $title, $authID, $date, $pending, $beta, $alpha, $tags, $views, $bites);
		mysqli_stmt_execute($stmt);
  		echo($id." | | ".mysqli_error($con));
    	$tempSQL="UPDATE tbl_news SET articleIDFK=".mysqli_insert_id($con)." WHERE id =".$row['id'];
    	mysqli_query($con,$tempSQL);
		echo "</td>";
		echo "<td>";
    	$counter++;
		/*echo "<tr>";
		echo "<td>";
		echo $counter."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["id"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["article_type"][0]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["title"]."<br />";
		echo "</td>";
		echo "<td>";
		$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
		$rowr= mysqli_fetch_row($resultr);
		echo $rowr[0];
		echo "</td>";
		echo "<td>";
		echo $row["createdate"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["pending"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["beta_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["alpha_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["tags"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["views"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["bites"]."<br />";
		echo "</td>";
		echo "</tr>";*/
=======
	echo "<tr>";
	echo "<td>";
	echo $row["id"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["article_type"][0]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["title"]."<br />";
	echo "</td>";
	echo "<td>";
	$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
	$rowr= mysqli_fetch_row($resultr);
	echo $rowr[0];
	echo "</td>";
	echo "<td>";
	echo $row["createdate"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["pending"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["beta_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["alpha_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["tags"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["views"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["bites"]."<br />";
	echo "</td>";
	echo "</tr>";
>>>>>>> 3b252456cedc9e1e2a4528e19dbbf0e4acfcb9eb
    }
    $sql = "SELECT * FROM tbl_guide";
    $result=mysqli_query($con,$sql);
    while($row = $result->fetch_assoc()) {
<<<<<<< HEAD
    	
		$Usersql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$Usersql);
		$rowr= mysqli_fetch_row($resultr);
		echo "<tr>";
		echo "<td>";
		$stmt = mysqli_prepare($con, "INSERT INTO tbl_article (`legacyID`, `article_type`, `title`, `authorUserFK`, `createdate`, `pending`, `beta_approved`, `alpha_approved`, `tags`, `views`, `bites`) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
		$id=$row['id'];
		$type=$row['article_type'][0];
		$title=$row['title'];
		$authID=$rowr[0];
		$date=$row['createdate'];
		$pending=($row['pending']=='true');
		$beta=($row['beta_approved']=='true');
		$alpha=($row['alpha_approved']=='true');
		$tags=$row['tags'];
		$views=$row['views']; 
		$bites=$row['bites'];
		mysqli_stmt_bind_param($stmt, "ississsssii", $id, $type, $title, $authID, $date, $pending, $beta, $alpha, $tags, $views, $bites);
		mysqli_stmt_execute($stmt);
  		echo($id." | | ".mysqli_error($con));
    	$tempSQL="UPDATE tbl_guide SET articleIDFK=".mysqli_insert_id($con)." WHERE id =".$row['id'];
    	mysqli_query($con,$tempSQL);
		echo "</td>";
		echo "<td>";
    	$counter++;
    	/*$counter++;
		echo "<tr>";
		echo "<td>";
		echo $counter."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["id"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["article_type"][0]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["title"]."<br />";
		echo "</td>";
		echo "<td>";
		$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";	
    	$resultr=mysqli_query($con,$sql);
		$rowr= mysqli_fetch_row($resultr);
		echo $rowr[0];
		echo "</td>";
		echo "<td>";
		echo $row["createdate"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["pending"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["beta_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["alpha_approved"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["tags"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["views"]."<br />";
		echo "</td>";
		echo "<td>";
		echo $row["bites"]."<br />";
		echo "</td>";
		echo "</tr>";*/
=======
	echo "<tr>";
	echo "<td>";
	echo $row["id"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["article_type"][0]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["title"]."<br />";
	echo "</td>";
	echo "<td>";
	$sql = "SELECT id FROM tbl_users WHERE username='".$row['authuser']."'";
    	$resultr=mysqli_query($con,$sql);
	$rowr= mysqli_fetch_row($resultr);
	echo $rowr[0];
	echo "</td>";
	echo "<td>";
	echo $row["createdate"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["pending"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["beta_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["alpha_approved"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["tags"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["views"]."<br />";
	echo "</td>";
	echo "<td>";
	echo $row["bites"]."<br />";
	echo "</td>";
	echo "</tr>";
>>>>>>> 3b252456cedc9e1e2a4528e19dbbf0e4acfcb9eb
    }
	echo "</table>";
echo "Complete no memory errors.<br>";
echo "</BODY></HTML>";
